version: '3'
services:
  db:
    image:  postgres:11
    ports:
      - 32700:5432
    volumes:
      - data:/var/lib/postgresql/data
    command: postgres -c stats_temp_directory=/tmp
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: accrt-dev-db
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    
volumes:
  data:
  pgadmin-data: